### ISSUE TITLE
Had to disable assertNoEval() for preg_get()

### ISSUE THREAD

**Issue by basepack** [jasny/twig-extensions#8] opened 2016-10-04 09:57 UTC
Hi,

I am matching the weeknumber in this string: `Week 38 - 2016`.

So I write the following: `{% set weeknumber = week|preg_get('/Week (?<weeknumber>[0-9]{1,})/', "weeknumber") %}`. 

Works perfectly, however I had to comment out the `assertNoEval()` call for the `get()` function. Maybe you can take a closer look at the assertNoEval function?

**Comment by jasny** [comment] 2017-01-12 22:24
Duplicate of #5

**Closed as completed** 2017-02-07 23:24 UTC
